# Batch install per the reinstall checklist. Must run as Administrator.
# Generated by Codex. Progress is written to install-log.txt in this folder.
# NOTE: keep this file ASCII-only. PowerShell 5.1 reads BOM-less UTF-8 scripts
#       as ANSI, which breaks parsing when Chinese characters are present.

$ErrorActionPreference = 'Continue'
$log = 'D:\Downloads\Installers\install-log.txt'

function Log([string]$m) {
    $line = "$(Get-Date -Format 'HH:mm:ss')  $m"
    Write-Host $line
    Add-Content -LiteralPath $log -Value $line -Encoding UTF8
}

Log '===== batch install start ====='

$packages = @(
    @{ n='Node.js LTS';      ids=@('OpenJS.NodeJS.LTS','OpenJS.NodeJS');  loc='C:\Dev\nodejs' },
    @{ n='Python 3.12';      ids=@('Python.Python.3.12');                 loc='C:\Dev\Python' },
    @{ n='DBeaver CE';       ids=@('DBeaver.DBeaver.Community');          loc=$null },
    @{ n='IntelliJ IDEA CE'; ids=@('JetBrains.IntelliJIDEA.Community');   loc=$null },
    @{ n='MySQL';            ids=@('Oracle.MySQL');                       loc=$null },
    @{ n='PostgreSQL';       ids=@('PostgreSQL.PostgreSQL.17','PostgreSQL.PostgreSQL.16','PostgreSQL.PostgreSQL.15'); loc=$null },
    @{ n='Docker Desktop';   ids=@('Docker.DockerDesktop');               loc=$null },
    @{ n='Logitech G HUB';   ids=@('Logitech.GHUB');                      loc=$null },
    @{ n='WeChat';           ids=@('Tencent.WeChat.Universal','Tencent.WeChat'); loc=$null },
    @{ n='Tencent Meeting';  ids=@('Tencent.TencentMeeting');             loc=$null },
    @{ n='Feishu';           ids=@('ByteDance.Feishu');                   loc=$null },
    @{ n='DingTalk';         ids=@('Alibaba.DingTalk.Mainland');          loc=$null },
    @{ n='WPS Office';       ids=@('Kingsoft.WPSOffice.CN','Kingsoft.WPSOffice'); loc=$null },
    @{ n='Steam';            ids=@('Valve.Steam');                        loc=$null },
    @{ n='Baidu Netdisk';    ids=@('Baidu.BaiduNetdisk');                 loc=$null }
)

$common = @('--silent','--accept-package-agreements','--accept-source-agreements','--disable-interactivity')

foreach ($p in $packages) {
    $ok = $false
    foreach ($id in $p.ids) {
        Log "-> $($p.n)  [$id]"
        $wgArgs = @('install','--id',$id,'-e') + $common
        if ($p.loc) { $wgArgs += @('--location', $p.loc) }

        $out  = & winget @wgArgs 2>&1 | Out-String
        $code = $LASTEXITCODE
        if ($code -eq 0) { Log '   OK installed'; $ok = $true; break }

        if ($p.loc) {
            Log '   .. custom location not supported, retry with default'
            $wgArgs2 = @('install','--id',$id,'-e') + $common
            $out  = & winget @wgArgs2 2>&1 | Out-String
            $code = $LASTEXITCODE
            if ($code -eq 0) { Log '   OK installed (default location)'; $ok = $true; break }
        }

        Log "   XX failed, exit code $code"
        ($out.Trim() -split "`n" | Select-Object -Last 2) | ForEach-Object { Log ('      ' + $_.Trim()) }
    }
    if (-not $ok) { Log "   !! $($p.n) needs manual handling" }
}

Log '===== batch install done ====='
